set encoding=utf-8

:ru mswin.vim

:set lines=35 columns=150

if has("win32")
  set guifont=Consolas:h11
  set guifontwide=新宋体:h10.5
endif

" set colorscheme to midnight. Use the command :colorscheme <schemeName> for setting other color schemes

colorscheme desert
set vb t_vb= " stop beeping or flashing the screen

"editor
set nocompatible
set backspace=2
set ruler
syntax on
set number
set wrap

" save, quit without save
nnoremap <C-x> :q!<CR>
nnoremap <C-o> :w<CR>

" toggle line number
nnoremap <S-l> :set invnu<CR>
" toggle line wrap
nnoremap <S-w> :set invwrap<CR>
" toggle syntax
nnoremap <S-s>
             \ : if exists("syntax_on") <BAR>
             \    syntax off <BAR>
             \ else <BAR>
             \    syntax enable <BAR>
             \ endif<CR>
" buffer
nnoremap <F5> :buffers<CR>:buffer<Space>
noremap <C-n> :bn<CR>
noremap <C-p> :bp<CR>

set laststatus=2

